### ISSUE TITLE
Support forceSend property for the 'log' action

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIPlayer#38] opened 2015-05-19 06:38 UTC
Sometimes we want a trial to be sent to the server immediately, so it would be nice to support the action:
{type:'log', forceSend:true}
By default forceSend will be false, of course. 
On forceSend, pip sends a message even if it is not time yet (by pulse).

**Comment by eladzlot** [comment] 2015-06-09 14:16
duplicate of #25

**Closed by eladzlot** 2015-06-09 14:16 UTC
